### ISSUE TITLE
Add Entity-Relationship (ER) model support

### ISSUE THREAD

**Issue by Mek101** [gaphor/gaphor#3158] opened 2024-02-29 11:13 UTC
I have not seen explicit support for entity-relationship models to project relational databases.
Would it be possible to add support for Entities, Attributes and Relationships?

**Comment by amolenaar** [comment] 2024-03-24 17:09
Closing this issue as duplicate of #1235. Let's continue discussing there.

**Closed by amolenaar** 2024-03-24 17:09 UTC
