### ISSUE TITLE
Malware detected from BitDefender when installing via winget

### ISSUE THREAD

**Issue by zooid** [gaphor/gaphor#3087] opened 2024-02-07 13:31 UTC
Malware detection on Gopher from BitDefender
![image](https://github.com/gaphor/gaphor/assets/1837230/4285bc24-5b5b-4a28-94e0-2a93b48ebc1b)

**Comment by amolenaar** [comment] 2024-02-07 15:45
Hi @zooid,

Thank for raising this. We've seen that the latest version 2.23.2 has triggered quite some anti-virus tools. Which is perculiar, considering the build chain for Windows builds everything from source without human interference.

We've been discussing this on our [Matrix channel](https://matrix.to/#/#gaphor_Lobby:gitter.im).

From the tests we've done so far, it looks like the binaries we're going to use to build 2.24 with will not trigger anti-virus software.

**Comment by amolenaar** [comment] 2024-02-07 15:46
I'll close this as a duplicate of #3086

**Closed by amolenaar** 2024-02-07 15:46 UTC
