### ISSUE TITLE
Model Tree Elements Disappear

### ISSUE THREAD

**Issue by kainne44** [gaphor/gaphor#865] opened 2021-06-21 15:53 UTC
What version are you using?
2.4.2

What operating system are you using?
Windows 10 Pro - 20H2 19042.1052

What did you do?
In an effort to reorder the model tree elements, I dragged an element above another such that it would stay within the same hierarchy level. I noticed a single green bar that seemed to indicate that a re-order of elements is acceptable, but when I released the mouse to place the element in its new position, it disappeared from the tree. Interestingly, the package and diagram view did not disappear. 

Further, I can move elements into a different hierarchy level. e.g. if I have a nested package and wanted to move it such that it is nested within a different package -- that works just fine.

What did you expect to see?
I expected to be able to reorder tree elements within a hierarchy level without the element disappearing from the tree.
e.g. I want to move the "Test 1" package above "Test 2" as shown below:
![image](https://user-images.githubusercontent.com/50899654/122790410-492bf400-d286-11eb-94eb-1f2a860da5ff.png)

and I expected this:
![image](https://user-images.githubusercontent.com/50899654/122791325-20582e80-d287-11eb-992b-66fa60023a0d.png)

What did you see instead?
It disappeared as shown below:
![image](https://user-images.githubusercontent.com/50899654/122790594-7678a200-d286-11eb-9eb7-d992efa9fafc.png)

Undo does not bring the package back. This also occurs with diagrams. As mentioned before, this doesn't delete the elements from existing diagrams, just removes their visibility from the tree.

Thank you!

**Comment by danyeaw** [comment] 2021-06-25 16:56
@kainne44 Thanks so much for reporting this bug, we really appreciate it! :gift: :+1: 

I can reproduce this in Windows as well with version 2.4.2 and the latest master version. I can't reproduce the issue in Linux, the packages don't disappear, but also don't allow for reordering.

Currently, elements are ordered by when they were created or last put in the parent package (top is newest). Should we allow for reordering through drag-and-drop? Should we instead reorder them always alphabetically?

@all-contributors please add @kainne44 for bug

**Comment by amolenaar** [comment] 2021-06-26 15:30
The items should be ordered in the tree view. However, in @kainne44's example they're not ordered it seems.

This is an interesting issue. Thanks for reporting 🙏.

**Comment by amolenaar** [comment] 2021-07-07 13:38
Finally my Windows setup works again. I can reproduce this behavior on Windows, not on mac and linux.

**Comment by danyeaw** [comment] 2021-07-08 01:37
@kainne44 This is now fixed with #882 merged. Thanks again @amolenaar for the fix!

**Closed by danyeaw** 2021-07-08 01:37 UTC
Labels: bug
