### ISSUE TITLE
General discussion - Diagram first, what does it mean?

### ISSUE THREAD

**Issue by sz332** [gaphor/gaphor#2577] opened 2023-07-29 04:02 UTC
We had a discussion with @mikekidner about diagram first approach. I would like to follow up this discussion and really tackle the problem from all sides to create a common understand what it means, what are the implications, and in the current maturity level whether it is relevant anymore.

**Comment by sz332** [comment] 2023-07-29 04:35
Let me start in a hope that people will jump into the discussion. According to my understanding when Gaphor was started the idea was that you create model elements through the diagrams. The reason for that was simplicity - which I totally agree - and consistency. 

Gaphor had a functionality of removing model elements that were not displayed on diagrams. However, it gave no feedback about this situation, and that was causing problems: you had no information about when you removed a diagram element, was it on another diagram displayed, or not? That might cause extremely serious issues, and I asked for clarification and for a solution. 

In #971 we had a long discussion about the topic and came to an understanding that the easiest way is to provide a configuration settings  disallowing the removal of such elements, and also displays an information if this feature is switched off about the situation of removal, so that the user can undo it.

Fast forward two years and Gaphor received a huge amount of improvements, but still following the original principles: simplicity, efficiency, less amount of disturbance, no hundreds of dialogs and complications, and good defaults. I think those are great values and should be pursued. 

Then there was a request to be able to create model elements in the tree, without having diagrams. The idea is that the same way as we create a package (or a diagram) we can create model elements using the menu. This would be a great feature in some situations, especially for more advanced modelers. But is it consistent with the principles? 

In my opinion we are talking about life-cycle management of model and diagram elements at this point, so let's go into the details. 

My first question is: what is the current status? What we are doing now? Is it true that every model element is being created through diagrams? The answer is packages. We are actually working in the model creating packages, that are model elements, without having a diagram. And to be honest, that's totally fine, and supports the needs of the modelers.

Then what is exactly the rule we are talking?

In reality, the rule does not say that a model element can exists only if there is a corresponding diagram element; it is not a constraint of the structure of the model!

It is but a behavior constraint: during the removal of a diagram element, if there are no other diagram elements point to the same model element, remove the model element as well (done by Sanitizer service). And even this behavior can be switched off even right now in the configuration.

On logical (conceptual) level, you simply cannot create a diagram element without creating a model element, so it cannot ever be a structural rule (unless they are being created in a transaction, but then, you are still having problems with packages).

So this is the current situation, and there is more. 

There is another caveat, and it is related to importing from external data source. As a modeler can you define upfront into which diagrams the thousands of model elements shall be added during the import process (requirements, api descriptions, whatever)? Or, would you more likely to import this information into a model without corresponding diagram elements, and later, gradually figure out on which view you'd like them to be presented?

What do you think, how should we think about model elements and diagrams now? How to create a common understanding, common principles that we should follow through the design?

**Comment by mikekidner** [comment] 2023-07-29 10:42
I do like the diagram-first principle, (yes the packages are an exception to the rule - but if you do start with a top level package diagram....).
I've had several comments from long term magic draw users praising the clean simplicity of the interface, and I think Gaphor should be hesitant to compromise on that. 
Using sysML directly to define the model also means that less training is required to use the tool. If you draw the diagram right the model will be right.

If the issue is efficiency, there are probably several UI-approaches that can speed up element creation and assist with managing model structure, for instance: 
more use of right-hand click menus within diagrams rather than dragging or combined keyboard-click interactions, 
right click to 'add ports', 'add pins'  etc, which would still be diagram driven, improved auto-layout

For data import, I imagine some structure would be known which would map to packages i.e requirements/RAMS/safety. The elements would land on package diagrams within that structure - rather than elements all at the top level

Another consideration might be sysMLv2;  the diagram view and the text view will need to stay in synch - and potentially the direct modelling.

I don't understand enough of the gaphor source code to appreciate how deep the implications of diagram-first vs model-first changes could go and I'm pretty new to MBSE, only working on small models (~1000 elements).

**Comment by sz332** [comment] 2023-07-29 11:18
> I do like the diagram-first principle, (yes the packages are an exception to the rule - but if you do start with a top level package >diagram....). I've had several comments from long term magic draw users praising the clean simplicity of the interface, and I think >Gaphor should be hesitant to compromise on that. 

Working primarily using diagrams does not mean you cannot work directly in the model as well. They are complementary functions: just because one modeler works primarily with diagrams does not mean others cannot start working in the model and then creating diagrams.

I totally agree that the interface should be as simple and clear (distraction free) as possible. However, I don't see how distracting is to have an additional menu item on right click in the tree. 

There was a video added to the other task, can you please took a look at it? What are your impressions?

https://github.com/gaphor/gaphor/issues/2552#issuecomment-1655018504

>Using sysML directly to define the model also means that less training is required to use the tool. If you draw the diagram right 
>the model will be right.

SysML (and UML training) absolutely takes time, and since creating model elements in the model directly is not mandatory, from the side of the people who are just using diagrams absolutely nothing will change. You can totally use a diagram first approach, no issues.

Just some side notes: I was training some of our new solution architects at my company and what absolutely made a difference for them was showing that a model element and a diagram element is not the same, a diagram is just a view of a model, that is acting as a database and they can query it, and modify it, and the views are being updated accordingly. Btw: we are also doing this: we can rename things in the model, which - again - says that feature wise we might be diagram first, but not diagram only! Maybe that's the difference?

>If the issue is efficiency, there are probably several UI-approaches that can speed up element creation and assist with managing >model structure, for instance: more use of right-hand click menus within diagrams rather than dragging or combined keyboard-
>click interactions, right click to 'add ports', 'add pins' etc, which would still be diagram driven, improved auto-layout

I like this idea, having for example a floating menu right beside the diagram element that is selected could enable faster modeling, absolutely. I think we could create a separate feature request for that.

> For data import, I imagine some structure would be known which would map to packages i.e requirements/RAMS/safety. The 
> elements would land on package diagrams within that structure - rather than elements all at the top level

Let's see how it would work. The modeler select an input file with 500 elements. We will create a diagram and will put 500 diagrams element randomly on it (or even ordered). The modeler then will create his own diagrams as it makes sense for his case, and basically drag and drop the corresponding model elements to the newly created diagrams. And at the end of the day he will delete the diagram element and hopes that nothing will be removed from the model. In my opinion it really does not make sense to enforce the creation of a diagram.
 
> Another consideration might be sysMLv2; the diagram view and the text view will need to stay in synch - and potentially the
> direct modelling.

AFAIK there is no restriction that you need to show every model element on a diagram. It is a limitation of the currently PlantUML based solution that you cannot really tell which model element you would like to present on a diagram and also where (in my opinion that is even the biggest limitation). Would love to see people from the SysML v2 standard being involved.

> I don't understand enough of the gaphor source code to appreciate how deep the implications of diagram-first vs model-first >changes could go and I'm pretty new to MBSE, only working on small models (~1000 elements).

I have been working with quite larger models (800k model elements) created by only a handful of modelers.

**Comment by mikekidner** [comment] 2023-07-29 22:45
> Working primarily using diagrams does not mean you cannot work directly in the model as well. They are complementary functions: just because one modeler works primarily with diagrams does not mean others cannot start working in the model and then creating diagrams.

Yes, that makes sense, as you say _Diagram first but not diagram only_. 

The video looks good, as noted in the issue - control over legal creation of elements will be important. Also I think that having done the modelling directly users may expect that the basic bdd diagram views could be generated automatically if required.

So the issue as you say is life-cycle-management of the model. The accumulation of redundant elements in the model, represented on diagrams or not, is still going to be an issue. As is ensuring valid structure.

In the example of importing 500 elements and then selecting from the model or diagram - how does the user clean up the unused ones? 
If they have been reallocated from the temporary import-diagrams then its shows they've been consciously used, so the remainder are candidates for deletion. 
From a model perspective, what is a good mechanism for identifying redundant elements - if non-use on a diagram is not a qualifier?

I think that good tools should make it easier to do the right thing and harder to do the wrong thing.  It will ultimately be a user responsibility to model well and keep their model coherent and correct - however, I think the tool can shape that thinking.
I feel that there are still several areas in the Gaphor where the modelling experience can be improved, and a diagram-centric approach does provide a framework for that. Where as direct model creation opens up more possibilities (both good and bad).

Perhaps, it's more about using the _language_ to create the model rather than using the tool. Thinking about this from a text based sysMLv2 perspective, the tool/editor should encourage correct use of the modelling language in order to create well formed models. A tool could be model based and then auto generate sysML _code_, or it could go the other way - valid sysML creates the model. After that, it is about good UI design.

**Comment by amolenaar** [comment] 2023-07-30 10:01
For me, diagram first means that we do not add information to a model that Gaphor cannot visualize in a diagram (or a table).

Diagrams can be created by hand, or can be created automatically. For example an element with all it's relations.


> ...what absolutely made a difference for them was showing that a model element and a diagram element is not the same, a diagram is just a view of a model...

I've seen questions along those lines for Gaphor too. If we could make that more clear from the application that would be a win, IMHO. Maybe #2545 is a step in that direction.

> ...feature wise we might be diagram first, but not diagram only.

The only restriction I want to put is that every bit of information that is part of a model _can_ be visualized. The exception that proves the rule is the remark field :wink: .

Visualization can be a diagram, but a table format (e.g. for the 500 elements) would also be a form of visualization.

> I think that good tools should make it easier to do the right thing and harder to do the wrong thing. It will ultimately be a user responsibility to model well and keep their model coherent and correct - however, I think the tool can shape that thinking.

I agree. It's a tricky question, though, since what's valid or not can depend a lot on the methodology you follow.

I think #2450, #2481, and #2554 are sort of related tickets.  

> I have been working with quite larger models (800k model elements) created by only a handful of modelers.

I do not think we should we should aim for this size.

**Comment by danyeaw** [comment] 2023-07-30 15:37
I think one of the things Diagram first represents is also Less is More. For UX, the underlying aim of this is simple: reducing the operational and cognitive costs of the users. In placing value on this, the design’s usability and consistency improve. I think this is a key advantage of Gaphor at the moment, and something we should continue to build on and optimize. There should only be a single or maybe 2 ways to accomplish something. SysML v2 is already adding some additional ways through diagrams, tables, and now simple code. There are probably some opportunities to add a little more capability to the Model Browser, but keeping it simple is also the balance we need to strike.

**Comment by marek-piirikivi** [comment] 2023-07-31 03:40
After reading the other comments it seems to me that "diagram first" is a matter of user experience question, not so much that every detail should be visible from the diagrams. UI should guide the user to not to think about the possibilities in how Gaphor can be used to create the model, rather about the model contents itself - eliminating the overhead of thinking about how to do something.

> what absolutely made a difference for them was showing that a model element and a diagram element is not the same, a diagram is just a view of a model

I have also the same experience. It has been a pivotal moment for myself in the past - and also now when I have shown people how to perform modelling - when I have asked them to forget about the diagrams and how it all looks in the diagram; and start thinking about the model as a whole.

I absolutely agree with both:

> For me, diagram first means that we do not add information to a model that Gaphor cannot visualize in a diagram (or a table).

and

> reducing the operational and cognitive costs of the users ... There should only be a single or maybe 2 ways to accomplish something

and I would conclude these points as:
- Every detail of the model shall be visualizable
- Let the user to perceive only limited options that the user can take

I have a strong favor for UI-s showing legal options that can be taken which would change the model state to the new desired state with as few steps as possible.

If we take a look at the example of "Creating new model elements in the model browser" vs. "Creating new model elements by selecting the element from the toolbox and placing it onto the diagram" then for both of these I could highlight:

"Creating new model elements in the model browser"
- The decision to create the new element originates by looking at the model in the model browser
- You put the new element directly in the model in its rightful location
- To show it in the diagram, you have to drag it to the diagram which solidifies the idea that diagrams show the model elements - emphasizing the element reusability across the diagrams. This is the motion you are forced to do to reuse the elements.

"Creating new model elements by selecting the element from the toolbox and placing it onto the diagram"
- The decision to create the new element originates by looking at the part of the model in the currently active diagram
- You put the new element in to diagram
- The element may not always go into the most rightful location in the model, but you can change it

"Diagram first" appears to be about the fact that every new element enters the model through a diagram. After that, the element selection goes through the model browser.

Regarding removing elements that are not seen on any diagrams; I would rather make this as a separate tool to firstly giving the ability to show/highlight unused elements if requested - elements which are not referenced from anywhere and do not trace to any diagrams. And then giving the user option to either manually delete them; or take them into a use; or just use tool action to delete all of them. I think "Diagram first" should not be about that everything is seen on the diagram, rather whether anything is traceable through the diagram. 

I would like to add an example of requirements. You have few activities shown on various diagrams and they are also satisfying requirements. The requirements themselves are not seen on any of the diagrams; but they are still related to the things that are seen on the diagrams - so they are not unused elements - they define the activities.

Overall, in conclusion, I would like to propose/encourage Gaphor to shift the focus from "diagram first" to "user experience" first. If it is proven that user experience is at its peak when everything goes through the diagram then "diagram first" applies, but I would not constrain the UX design with "diagram first" principle; rather it should be constrained by simple to understand UI that shows legal options where they are expected and when needed which would help the user to define the model in the least amount of steps.

**Comment by danyeaw** [comment] 2023-07-31 10:44
I think with Diagram First that we are saying that we value use case 2 over use case 1. That doesn't mean that use case 1 with the Model Browser isn't important, it just means that we give more value to creating elements via a diagram.

This helps guide UX, because that then leads to us not fully developing both use cases in the tool because we have prioritized optimizing one. Diagram first is us prioritizing this easy path for users which helps with the less is more principle.

**Comment by sz332** [comment] 2023-07-31 16:41
Thank you for all the comments, I think this is a really productive discussion and helps us to create a common understanding.

Some things just came in my mind, so let's take the following use cases:

1, Create model element in the model and drag it onto the diagram
2, Create model element directly through the diagram

Are these use cases covering? Actually not, because we tend to forget that a diagram is just a view, and it is totally valid (and often used functionality) is to present the same element on multiple diagrams. So, let's rethink the use cases.

1, Create model element in the model (model element)
2, Create model element through a diagram (both model element and diagram element)
3, Drag an existing model element onto a diagram (diagram element)

I would argue that even now, we have each and every use case covered (although not for every element):

1, Example: creation of a package using the menu
2, Example: creating a class on a class diagram using the toolbar
3, Example: Drag an existing class from the model into a new class diagram

So at the end of the day, the way I understand we are talking about the prioritization of the previous use cases like:

1, Diagram element creation with model element creation
2, Drag and drop from model to diagram
3, Creation of model elements

Even with the super optimization we need to cover use cases 1 and 2. That is the absolutely must. Use case 3 is although a nice addition, but not mandatory. 

What do you think about this way of thinking?

**Comment by pinxue** [comment] 2023-08-24 07:59
Per my experience, it is good enough:
1. Toolbox always create new item in diagram and model
2. Dragging model tree item into diagram always create a view-reference only
3. Connection creating or breaking by dragging in diagram always create item in diagram and model, even if there is already some connections between them, but remove only those affected (visible at the moment) from diagram
4. Removing from diagram only by default
5. "Remove from model at same time" is a specific operation by menu item or shortcut (shift-del or similar) in diagram view
6. Removing from model is cascade deleting
7. Make connection easier to identify in model tree (hint about from-to for no-name, or possible to hide name in diagram for naming everyone without messing up in view)
8. Keep "remove unused" as a vacuum, default off is better for me but that is not an issue

**Comment by amolenaar** [comment] 2024-02-24 19:10
Since there's no action needed from this issue, I think we can close this.

(feel free to reopen if you disagree ;) )

**Closed by amolenaar** 2024-02-24 19:10 UTC
Labels: ideation
