### ISSUE TITLE
Translations not available in Windows build

### ISSUE THREAD

**Issue by oscfdezdz** [gaphor/gaphor#1969] opened 2022-12-28 22:51 UTC
### Describe the bug
Gaphor builds for Windows do not seem to have translations available.

### To Reproduce
1. Run installer or portable executables of Gaphor.
2. Open Gaphor.
3. See that UI language does not follow system language although is available, in my case Spanish.

### Expected behavior
See Gaphor UI translated.

### OS
- [ ] Linux
- [ ] macOS
- [x] Windows

### Version
Version of Gaphor: 2.14.2

**Comment by danyeaw** [comment] 2022-12-29 14:39
Thanks @oscfdezdz for the bug report! This isn't something I normally see because my computers are set for English, so I really appreciate you pointing this out. I can reproduce this on Windows as well.

**Comment by danyeaw** [comment] 2022-12-29 16:47
I think one of the bugs here was fixed by @amolenaar in d933bca62c7bf822219466788f8cef5fd1a4338f, since we weren't opening the translation files with utf-8. However, that change made it in to 2.14.2.

It works for me to set my environmental variable with `set LANG='es_ES.utf-8'` or `$env:LANG='es_ES.utf-8`, does that work for you as well?

Then the next step is how do we get Gaphor to pick up the selected language by default.

**Comment by oscfdezdz** [comment] 2022-12-29 17:52
> It works for me to set my environmental variable with `set LANG='es_ES.utf-8'` or `$env:LANG='es_ES.utf-8`, does that work for you as well?

It doesn't work for me, I tried both of them in PowerShell as I would have done on Linux and running Gaphor afterwards. Maybe I'm doing it wrong as I'm not used to doing this kind of stuff on Windows.

**Comment by danyeaw** [comment] 2022-12-29 18:27
Yes, you are right, it will only work for me when running from source - not when the app is packaged.

**Comment by amolenaar** [comment] 2022-12-30 14:15
Fixed by #1973.

**Closed by amolenaar** 2022-12-30 14:15 UTC
Labels: bug
