### ISSUE TITLE
Unable to enter Chinese in the pop-up box

### ISSUE THREAD

**Issue by JACKADUX** [gaphor/gaphor#3238] opened 2024-04-04 13:44 UTC
### Describe the bug
Unable to enter Chinese in the pop-up box

### To Reproduce
1. Double click Block
2. Enter Chinese
3. Unable to enter

The property bar on the right can be entered normally.

### Expected behavior
Enter Chinese normally

### Screenshots
![recording](https://github.com/gaphor/gaphor/assets/87265559/eb6f814b-5a75-4536-8aed-a1ff2bbc4e66)

### OS
- [ ] Linux (Please put in notes the specific distro)
- [ ] macOS
- [x] Windows

### Version
Version of Gaphor: v2.24.0

**Comment by danyeaw** [comment] 2024-04-06 01:56
Yup, I agree that this is a duplicate of #2647. Thanks @JACKADUX for the issue report, but I'm going to close this one.

**Closed by danyeaw** 2024-04-06 01:56 UTC
