### ISSUE TITLE
Swim Lane diagrams do not appear correctly in 2.23

### ISSUE THREAD

**Issue by jim-gardiner** [gaphor/gaphor#3003] opened 2024-01-10 13:32 UTC
### Describe the bug
trying to follow youtube tutorial. section where swimlanes are added is not possible in 2.23, reverted to 2.22.1 and they are rendered correctly.

**Comment by danyeaw** [comment] 2024-01-10 16:51
Hi @jim-gardiner, thanks for submitting the issue. This is a duplicate of #2988 and has been fixed. We are working on getting a new release out soon.

**Closed** 2024-01-10 16:51 UTC

**Comment by jim-gardiner** [comment] 2024-01-10 16:55
thanks, I realise now I searched open issues, not closed issues.
