### ISSUE TITLE
macOS: Can't Resize Coffee Machine Model

### ISSUE THREAD

**Issue by danyeaw** [gaphor/gaphor#3077] opened 2024-02-03 21:18 UTC
### Describe the bug
The coffee machine example model at `examples/coffee-machine.gaphor` loads fine, but then you can't resize the Window in macOS. Clicking the maximize button has no effect and the resize arrows don't show up when hovering around the edge of the Window.

### To Reproduce
1. Open the coffee machine example in macOS
2. Try to resize the window

### Expected behavior
Maximize button and resize of the window works.

### OS
- [ ] Linux (Please put in notes the specific distro)
- [X] macOS
- [ ] Windows

### Version
Version of Gaphor: latest main and 2.23.2

**Comment by leftbrainstuff** [comment] 2024-02-06 08:49
Same issue. Gaphor opens in a view about 1/4 the screen size. Can move the view around but cannot maximise. Maximise option is greyed out too. View also snaps to top left of screen when dragging the view by clicking in the header.

**Comment by amolenaar** [comment] 2024-02-07 16:02
I cannot reproduce this. Resizing seems to work fine. But I have gtk installed via homebrew... Would that make a difference?

**Comment by danyeaw** [comment] 2024-02-07 23:15
Interesting, I have GTK and Gaphor installed via Homebrew.

**Comment by leftbrainstuff** [comment] 2024-02-08 08:32
Which version of gtk do you have installed? Just tried gtk+3 and no change. I notice that gaphor, installed using Brew has no installed dependencies; using 'brew deps gaphor', so suspect installing GTK, or any other library will have no impact on this issue, as Brew on mac installs the .dmg. Still haven't root caused this issue. The entry screen works fine, the problem exists when a model is loaded.

**Comment by amolenaar** [comment] 2024-02-08 16:43
This looks like a GTK issue: https://gitlab.gnome.org/GNOME/gtk/-/issues/5898.

**Comment by amolenaar** [comment] 2024-03-06 07:14
MR is merged and will be available in GTK 4.14.0.

**Comment by amolenaar** [comment] 2024-03-18 13:47
4.14 has been released and will he used for the next Gaphor release for macOS (it's in Homebrew).

**Closed by amolenaar** 2024-03-18 13:47 UTC
Labels: bug, upstream, macOS
