### ISSUE TITLE
Values support for SysML block diagrams

### ISSUE THREAD

**Issue by sz332** [gaphor/gaphor#972] opened 2021-09-11 19:53 UTC
As a user I would like to be able to define values in a SysML block diagram.

**Comment by amolenaar** [comment] 2021-09-12 13:29
Hi @sz332,

Is this related to #701?

**Comment by sz332** [comment] 2021-09-12 14:16
Yes

**Comment by danyeaw** [comment] 2021-09-12 17:20
Thanks for opening the issue, but I think we should only track this in one place. Closing as duplicate of #701.

**Closed by danyeaw** 2021-09-12 17:20 UTC
