### ISSUE TITLE
Mac Gaphor 2.0 failing to open Windows Gaphor 1.2.0rc2 .gaphor file

### ISSUE THREAD

**Issue by Xander982** [gaphor/gaphor#384] opened 2020-08-01 23:50 UTC
<img width="822" alt="Screen Shot 2020-08-01 at 7 05 27 PM" src="https://user-images.githubusercontent.com/51178927/89112423-41761d80-d430-11ea-85a6-51d02058faf0.png">

### I'm submitting a...
- [X] Bug report  
- [ ] Feature request
- [ ] Documentation issue or request

### Current behavior

I just tried to open an .gaphor file from a Windows install prior to today in a fresh Gaphor 2.0 install on a Mac and Gaphor coughed at that.
"Error while loading model from file
Technical details: <class 'gaphor.storage.parser.ParserException'> Invalid XML: tag <html> not known (state=0)"

### Expected behavior
Open the .gaphor file without errors!

### Minimal reproduction of the problem with instructions
Try saving a .gaphor file on a Windows Gaphor 1.2 and opening it in Mac Gaphor 2.0
### If this is a feature request please fill out the following:
<pre><code>
As a (user, developer, contributor, etc):
I want:
So that:

</code></pre>

### System Information
OS:
- [ ] Linux (Please put in notes the specific distro)
- [X] MacOS
- [ ] Windows 10
- [ ] Windows 7

NOTES:

**Comment by Xander982** [comment] 2020-08-02 14:13
See my most recent Gist for the .gaphor file

**Comment by amolenaar** [comment] 2020-08-03 09:01
Hi @Xander982, I can not find your .gaphor file. I like to investigate this issue.

**Comment by danyeaw** [comment] 2020-08-05 01:09
Thanks @Xander982 for the bug report! The gist is here:
https://gist.github.com/Xander982/d2fd89e6dfcbad94f7264dfdc10d2448

**Comment by amolenaar** [comment] 2020-08-07 19:37
@danyeaw @Xander982 Ehhmm.. This gist contains an HTML file.

**Comment by danyeaw** [comment] 2020-08-08 19:37
@Xander982 Can you open your gaphor file in a code editor (Visual Studio Code, Pycharm, etc) and then paste it in a gist or do you want to just email me a copy at dan@yeaw.me?

**Comment by amolenaar** [comment] 2020-08-10 07:07
@Xander982 I downloaded the gaphor file gists as zip files and tested them on my Mac. What steps did you take to load the model on Mac? Did you open it directly from Finder?

Using the open dialog in Gaphor I can open the model. When trying to open it from Finder I see some inconsistencies and errors in the Console:
<img width="952" alt="image" src="https://user-images.githubusercontent.com/96249/89758588-76e1d180-dae8-11ea-82cd-d5dded10a253.png">
<img width="942" alt="image" src="https://user-images.githubusercontent.com/96249/89758618-895c0b00-dae8-11ea-8377-5877a28ac95b.png">

But then it's not opening the model at all. No parse errors or anything.

Maybe you can share a dropbox link? Since I can not reproduce the error using the gists.

**Comment by danyeaw** [comment] 2020-08-12 23:51
@Xander982 Want to give the updated build a whirl and see if this fixes your issue? https://github.com/gaphor/gaphor/suites/1039287513/artifacts/13851650

@amolenaar Do you think it would be worth cutting v2.0.1 to fix this?

**Comment by amolenaar** [comment] 2020-08-13 05:26
I think it's worth a new release. There are a couple of small fixed.

**Comment by Xander982** [comment] 2020-08-13 12:35
[image: Screen Shot 2020-08-13 at 8.33.14 AM.png]
Crashed Thread:        0

Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Termination Reason:    DYLD, [0x1] Library missing

Application Specific Information:
dyld: launch, loading dependent libraries

Dyld Error Message:
  Library not loaded: @executable_path/../Resources/lib/libgtk-3.0.dylib
  Referenced from:
/Applications/Gaphor.app/Contents/Resources/bin/gtk-query-immodules-3.0
  Reason: image not found

--------
Crashed Thread:        0

Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Termination Reason:    DYLD, [0x1] Library missing

Application Specific Information:
dyld: launch, loading dependent libraries

Dyld Error Message:
  Library not loaded: @executable_path/../Resources/lib/libglib-2.0.0.dylib
  Referenced from:
/Applications/Gaphor.app/Contents/Resources/bin/gdk-pixbuf-query-loaders
  Reason: image not found

**Comment by Xander982** [comment] 2020-08-13 12:38
That was trying to open Gaphor via clicking on a .gaphor file.  The same
thing happens when you click on Gaphor itself.

**Comment by amolenaar** [comment] 2020-08-14 07:09
I also noticed that just clicking a gaphor file did not open Gaphor. I fixed that with #394. It should work on the latest snapshot. 

Caveat: I've installed all dependencies via Homebrew, so for me it works. I'll have to check with all libraries de-installed as well.

**Comment by amolenaar** [comment] 2020-08-14 09:05
I did uninstall homebrew and get a similar error:

```
** (process:42404): WARNING **: 10:20:07.198: Failed to load shared library 'libpango-1.0.0.dylib' referenced by the typelib: dlopen(libpango-1.0.0.dylib, 9): image not found
```
I have to dig into this.

**Comment by danyeaw** [comment] 2020-08-15 18:06
@Xander982 Would you mind testing this updated version?

**Comment by Xander982** [comment] 2020-08-17 21:02
Sorry.  I'm catching up.  Am I just downloading the .dmg from gaphor.org or
using homebrew to install something from github?

**Comment by danyeaw** [comment] 2020-08-17 23:53
@Xander982 Download the dmg from here: https://github.com/gaphor/gaphor/actions/runs/208362940

**Comment by Xander982** [comment] 2020-08-19 01:59
The program starts to open and then stops before the window appears.

**Comment by Xander982** [comment] 2020-08-19 02:00
It does the same thing when I click on a Gaphor file.

**Comment by amolenaar** [comment] 2020-08-20 19:58
Can you find something in the Console when you launch the application? Is the application "allowed" in the System preferences?

**Comment by amolenaar** [comment] 2020-08-26 12:48
@Xander982 I found that if you start it from the DMG directly it will fail. It's not able to build the pixbuf and im-modules caches. This is an issue I have to address.

**Comment by amolenaar** [comment] 2020-08-26 16:44
@Xander982 I fixed the loading issue on "fresh" macs. Can you give it a try? The build that fixed it is https://github.com/gaphor/gaphor/actions/runs/225534055

**Comment by amolenaar** [comment] 2020-08-26 18:12
@Xander982 @danyeaw I think the issue with loading Gaphor is fixed now. I tried with and without existing cache files.

Xander, can you give this build a try? https://github.com/gaphor/gaphor/actions/runs/225697365

**Comment by Xander982** [comment] 2020-08-27 12:26
Yes, it opened!  Just needed to do the "open with" command to get past the
MacOS security.

**Comment by danyeaw** [comment] 2020-08-28 00:31
@Xander982 Thanks again for reporting the bug and helping to confirm it is fixed.

@amolenaar :tada:

**Closed by danyeaw** 2020-08-28 00:31 UTC
Labels: bug

**Comment by amolenaar** [comment] 2020-08-29 20:45
Sweet! Thanks @Xander982!
