### ISSUE TITLE
Composite association between Actor and Block breaks model

### ISSUE THREAD

**Issue by ascaron37** [gaphor/gaphor#1704] opened 2022-09-03 05:31 UTC
### Describe the bug
When connecting an actor with a block in a BDD with a composite association the model file gets corrupted.

### To Reproduce
1. Create a new generic model
2. Switch to the SysML profile
3. Add a block to the main BDD
4. Add an actor to the main BDD
5. Connect actor and block with a composite association
6. Error message appears
7. Undo the association
8. Save file
9. Close model
10. Open model
11. Model is now empty, no errors are reported

When going through steps 1. to 7. it is also impossible to create new composite associations between blocks.

```
OS: Windows (10)
Python version: 3.10.5
GTK version: 3.24.33
Gaphor version: 2.11.0

Errors:

Time since application startup: 0:01:49
|Traceback (most recent call last):
|  File "C:\Program Files (x86)\Gaphor\gaphor\diagram\tools\placement.pyc", line 109, in on_drag_end
|  File "C:\Program Files (x86)\Gaphor\gaphor\diagram\tools\placement.pyc", line 94, in connect_opposite_handle
|  File "C:\Program Files (x86)\Gaphor\gaphor\diagram\tools\grayout.pyc", line 53, in connect
|  File "C:\Program Files (x86)\Gaphor\gaphas\handlemove.pyc", line 105, in connect
|  File "C:\Program Files (x86)\Gaphor\gaphor\transaction.pyc", line 169, in _transactional
|  File "C:\Program Files (x86)\Gaphor\gaphor\diagram\tools\connector.pyc", line 62, in connect
|  File "C:\Program Files (x86)\Gaphor\gaphor\diagram\connectors.pyc", line 316, in connect
|  File "C:\Program Files (x86)\Gaphor\gaphor\UML\classes\classconnect.pyc", line 144, in connect_subject
|  File "C:\Program Files (x86)\Gaphor\gaphor\UML\classes\classconnect.pyc", line 126, in relationship_or_new
|  File "C:\Program Files (x86)\Gaphor\gaphor\UML\classes\classconnect.pyc", line 108, in new_relation
|  File "C:\Program Files (x86)\Gaphor\gaphor\UML\recipes.pyc", line 240, in create_association
|  File "C:\Program Files (x86)\Gaphor\gaphor\UML\recipes.pyc", line 317, in set_navigability
|AttributeError: 'Actor' object has no attribute 'ownedAttribute'
└─────────────────────────────╌┄┈
Time since application startup: 0:01:49
|Traceback (most recent call last):
|  File "C:\Program Files (x86)\Gaphor\gaphor\diagram\tools\txtool.pyc", line 38, in on_end
|  File "C:\Program Files (x86)\Gaphor\gaphor\diagram\tools\txtool.pyc", line 20, in commit
|  File "C:\Program Files (x86)\Gaphor\gaphor\transaction.pyc", line 69, in commit
|  File "C:\Program Files (x86)\Gaphor\gaphor\transaction.pyc", line 110, in _handle
|  File "C:\Program Files (x86)\Gaphor\gaphor\core\eventmanager.pyc", line 64, in handle
|  File "C:\Program Files (x86)\Gaphor\generic\event.pyc", line 61, in handle
|exceptiongroup.ExceptionGroup: Error while handling events (1 sub-exception)
└─┬──────────────────────────────╌┄┈
  |Traceback (most recent call last):
  |  File "C:\Program Files (x86)\Gaphor\generic\event.pyc", line 57, in handle
  |  File "C:\Program Files (x86)\Gaphor\gaphor\services\undomanager.pyc", line 181, in rollback_transaction
  |  File "C:\Program Files (x86)\Gaphor\gaphor\transaction.pyc", line 169, in _transactional
  |  File "C:\Program Files (x86)\Gaphor\gaphor\services\undomanager.pyc", line 71, in execute
  |  File "C:\Program Files (x86)\Gaphor\gaphor\services\undomanager.pyc", line 325, in undo_create_event
  |  File "C:\Program Files (x86)\Gaphor\gaphor\core\modeling\element.pyc", line 160, in unlink
  |  File "C:\Program Files (x86)\Gaphor\gaphor\core\modeling\presentation.pyc", line 105, in inner_unlink
  |  File "C:\Program Files (x86)\Gaphor\gaphas\connections.pyc", line 162, in remove_connections_to_item
  |  File "C:\Program Files (x86)\Gaphor\gaphas\connections.pyc", line 148, in _disconnect_item
  |  File "C:\Program Files (x86)\Gaphor\gaphor\diagram\tools\connector.pyc", line 109, in __call__
  |  File "C:\Program Files (x86)\Gaphor\generic\multidispatch.pyc", line 131, in __call__
  |  File "C:\Program Files (x86)\Gaphor\gaphor\UML\classes\classconnect.pyc", line 68, in __init__
  |  File "C:\Program Files (x86)\Gaphor\gaphor\diagram\connectors.pyc", line 155, in __init__
  |  File "C:\Program Files (x86)\Gaphor\gaphor\diagram\connectors.pyc", line 70, in __init__
  |AssertionError: Cannot connect with different diagrams (<gaphor.UML.classes.klass.ClassItem element 8c56c84a-2b45-11ed-ade7-d4258b5d248c>: <gaphor.core.modeling.diagram.Diagram element 58d6c536-66f8-11ec-b4c8-0456e5e540ed>, <gaphor.UML.classes.association.AssociationItem element eb51fa78-2b46-11ed-9272-d4258b5d248c>: None)
  └─────────────────────────────╌┄┈
Time since application startup: 0:01:49
|Traceback (most recent call last):
|  File "C:\Program Files (x86)\Gaphor\gaphas\decorators.pyc", line 86, in async_wrapper
|  File "C:\Program Files (x86)\Gaphor\gaphas\view\gtkview.pyc", line 318, in update
|  File "C:\Program Files (x86)\Gaphor\gaphas\decorators.pyc", line 126, in wrapper
|  File "C:\Program Files (x86)\Gaphor\gaphor\core\modeling\diagram.pyc", line 395, in update_now
|  File "C:\Program Files (x86)\Gaphor\gaphas\connections.pyc", line 74, in solve
|  File "C:\Program Files (x86)\Gaphor\gaphas\solver\solver.pyc", line 178, in solve
|  File "C:\Program Files (x86)\Gaphor\gaphas\solver\constraint.pyc", line 105, in solve
|  File "C:\Program Files (x86)\Gaphor\gaphas\position.pyc", line 161, in solve_for
|  File "C:\Program Files (x86)\Gaphor\gaphas\position.pyc", line 64, in _set_y
|  File "C:\Program Files (x86)\Gaphor\gaphas\solver\variable.pyc", line 111, in set_value
|  File "C:\Program Files (x86)\Gaphor\gaphas\solver\variable.pyc", line 90, in notify
|  File "C:\Program Files (x86)\Gaphor\gaphas\position.pyc", line 50, in _propagate_y
|  File "C:\Program Files (x86)\Gaphor\gaphas\position.pyc", line 42, in notify
|  File "C:\Program Files (x86)\Gaphor\gaphor\diagram\presentation.pyc", line 99, in _on_handle_position_update
|  File "C:\Program Files (x86)\Gaphor\gaphor\core\modeling\element.pyc", line 174, in handle
|  File "C:\Program Files (x86)\Gaphor\gaphor\core\modeling\elementfactory.pyc", line 224, in handle
|  File "C:\Program Files (x86)\Gaphor\gaphor\core\eventmanager.pyc", line 64, in handle
|  File "C:\Program Files (x86)\Gaphor\generic\event.pyc", line 61, in handle
|exceptiongroup.ExceptionGroup: Error while handling events (1 sub-exception)
└─┬──────────────────────────────╌┄┈
  |Traceback (most recent call last):
  |  File "C:\Program Files (x86)\Gaphor\generic\event.pyc", line 57, in handle
  |  File "C:\Program Files (x86)\Gaphor\gaphor\services\undomanager.pyc", line 367, in undo_delete_element_event
  |  File "C:\Program Files (x86)\Gaphor\gaphor\services\undomanager.pyc", line 152, in add_undo_action
  |gaphor.services.undomanager.NotInTransactionException: Updating state outside of a transaction.
  └─────────────────────────────╌┄┈
Time since application startup: 0:01:53
|Traceback (most recent call last):
|  File "C:\Program Files (x86)\Gaphor\gaphor\ui\mainwindow.pyc", line 276, in _on_window_active
|  File "C:\Program Files (x86)\Gaphor\gaphor\core\eventmanager.pyc", line 64, in handle
|  File "C:\Program Files (x86)\Gaphor\generic\event.pyc", line 61, in handle
|exceptiongroup.ExceptionGroup: Error while handling events (1 sub-exception)
└─┬──────────────────────────────╌┄┈
  |Traceback (most recent call last):
  |  File "C:\Program Files (x86)\Gaphor\generic\event.pyc", line 57, in handle
  |  File "C:\Program Files (x86)\Gaphor\gaphor\services\undomanager.pyc", line 367, in undo_delete_element_event
  |  File "C:\Program Files (x86)\Gaphor\gaphor\services\undomanager.pyc", line 152, in add_undo_action
  |gaphor.services.undomanager.NotInTransactionException: Updating state outside of a transaction.
  └─────────────────────────────╌┄┈
```

### Expected behavior
I am fairly new to SysML/UML and I guess the association between an actor and a block in BDD is not allowed. But I would expect to receive a error message and to not break the model.
![empty_model](https://user-images.githubusercontent.com/8329544/188257156-2583d677-329e-42b7-9108-60a4164e925a.PNG)

### OS
- [ ] Linux (Please put in notes the specific distro)
- [ ] macOS
- [x] Windows 10

### Version
Version of Gaphor: 2.11.0

### Additional information
Diffing the model file with the actor and the block before the association and after this snippet gets added:
```
<AssociationItem id="eb51fa78-2b46-11ed-9272-d4258b5d248c">
<diagram>
<ref refid="58d6c536-66f8-11ec-b4c8-0456e5e540ed"/>
</diagram>
<horizontal>
<val>0</val>
</horizontal>
<preferred_aggregation>
<val>composite</val>
</preferred_aggregation>
<matrix>
<val>(1.0, 0.0, 0.0, 1.0, 585.0, 397.0)</val>
</matrix>
<points>
<val>[(-35.0, 9.25), (-176.0, 441.0)]</val>
</points>
<head-connection>
<ref refid="8c56c84a-2b45-11ed-ade7-d4258b5d248c"/>
</head-connection>
<tail-connection>
<ref refid="954b3064-2b45-11ed-8893-d4258b5d248c"/>
</tail-connection>
</AssociationItem>
```

**Comment by amolenaar** [comment] 2022-09-03 15:02
@ascaron37 Thank you for this report. I can reproduce it.

I can see a similar issue when I connect a class and a actor/usecase with a normal assocation. The core of the problem is:

```
AttributeError: 'Actor' object has no attribute 'ownedAttribute'
```

The rest are cascading errors. Actors and UseCases have no `ownedAttribute`'s relation by themselves.

**Comment by ascaron37** [comment] 2022-09-04 07:55
Wow! That was fast... thank you very much!

**Comment by amolenaar** [comment] 2022-09-04 12:54
@ascaron37  The fix will be in the next release. Is it okay for you to use dependency lines in the mean time?

**Comment by ascaron37** [comment] 2022-09-04 13:35
@amolenaar Of course! Again, thank you so much for your time and help.

I started learning model-based systems engineering last week and it is so confusing to learn a formal language (SysML), a complex tool (Enterprise Architect) and a SE methodology at the same time. Additionaly to EA I try to model everything in gaphor as well and it is awesome how easy it is. Thank you very much for your work!

**Comment by amolenaar** [comment] 2022-09-04 14:20
@ascaron37 Thank you for your appreciation and kind words. That's what makes it worth building a tool like this :+1:.

**Comment by danyeaw** [comment] 2022-09-05 19:02
@all-contributors please add @ascaron37 for bug

**Closed** 2022-09-05 19:01 UTC
Labels: bug
