### ISSUE TITLE
Only shows the list of diagrams

### ISSUE THREAD

**Issue by jistro** [gaphor/gaphor#2206] opened 2023-04-02 22:48 UTC
### Describe the bug
only shows the list of diagrams.

### To Reproduce
1. Make a file
2. Dont save and close the program
3. Reopen 

Gaphor version:    2.17.0
Operating System:  Windows (10)
Python version:    3.11.2
GTK version:       4.8.3
Adwaita version:   1.2.1
PyGObject version: 3.42.2
Pycairo version:   1.23.0
Cairo version:     1.17.8
Pango version:     1.50.12
Display:           GdkWin32Display

Errores:

Time since application startup: 0:00:24
|Traceback (most recent call last):
|  File "C:\Program Files\Gaphor\gaphor\ui\treecomponent.pyc", line 354, in on_show_popup
|AttributeError: 'MultiSelection' object has no attribute 'get_selected'
└─────────────────────────────╌┄┈

### Expected behavior
view the entire interface

### Screenshots
![image](https://user-images.githubusercontent.com/22781439/229383157-66d26087-c8b6-44a7-8baa-be64e5789a79.png)

### OS
- [ ] Linux (Please put in notes the specific distro)
- [ ] macOS
- [x] Windows

### Version
Version of Gaphor: 2.17.0

**Comment by amolenaar** [comment] 2023-04-03 06:31
Hi @jistro, Thanks for reporting the issue.

It's a duplicate of #2107.

We're close to a new release :)

**Closed by amolenaar** 2023-04-03 06:31 UTC
