### ISSUE TITLE
'MultiSelection' object has no attribute 'get_selected'. Did you mean: 'get_selection'?

### ISSUE THREAD

**Issue by Psycomentis06** [gaphor/gaphor#2144] opened 2023-03-10 16:38 UTC
### Describe the bug
Whenever I right-click on the sidebar to make a new Package, I get this error

### To Reproduce

If possible, add the error report from `≡` (top-right menu) → `Tools` → `Error Reports`.

Gaphor version:    2.17.0
Operating System:  Linux (6.1.8-1-vanilla)
Python version:    3.10.6
GTK version:       4.8.3
Adwaita version:   1.2.2
PyGObject version: 3.42.2
Pycairo version:   1.23.0
Cairo version:     1.16.0
Pango version:     1.50.12
Display:           X11Display

Errors:

```
Time since application startup: 0:00:40
|Traceback (most recent call last):
|  File "/app/lib/python3.10/site-packages/gaphor/ui/treecomponent.py", line 354, in on_show_popup
|    selection.unselect_item(selection.get_selected())
|    │                       └ <Gtk.MultiSelection object at 0x7ff0617345c0 (GtkMultiSelection at 0x55ca136478c0)>
|    └ <Gtk.MultiSelection object at 0x7ff0617345c0 (GtkMultiSelection at 0x55ca136478c0)>
|AttributeError: 'MultiSelection' object has no attribute 'get_selected'. Did you mean: 'get_selection'?
└─────────────────────────────╌┄┈
```

**Comment by amolenaar** [comment] 2023-03-11 13:18
Hi,

Thank you for reporting. This is a duplicate of #2107. It will be fixed in the next release.

@all-contributors add @Psycomentis06 for bug

**Closed** 2023-03-11 13:18 UTC
