### ISSUE TITLE
Color Picker Widget

### ISSUE THREAD

**Issue by vanillajonathan** [gaphor/gaphor#2136] opened 2023-03-08 11:28 UTC
### Is your feature request related to a problem?
Not everyone knows CSS and it can be tricky for some people to know how to style using CSS even if they're familiar with CSS.

### Describe the solution you'd like
I would like a color picker in the property editor to easily be able to assign a background color to a node such as a class or a component.

**Comment by danyeaw** [comment] 2023-03-08 23:25
Thanks @vanillajonathan, this is a duplicate of #2115

**Comment by vanillajonathan** [comment] 2023-03-09 12:05
This issue is not about toggling dark mode, I want a color picker widget to change the color of a node such as a class, component or interface in WYSIWYG manner.

**Comment by FranciscoTGouveia** [comment] 2024-04-26 10:21
Hi! Me and my colleague @0lione have realized that not many people are familiar with *CSS*, and that can be an obstacle for some Gaphor users while using the style sheet. With that being said, we would like to take on this issue, creating an interface to abstract the *CSS* and offer a more *user-friendly* way of changing colors. Would it be possible for us to be assigned to this issue? Thanks in advance.

**Comment by amolenaar** [comment] 2024-04-27 13:01
@FranciscoTGouveia @0lione Do you have an idea on how to make CSS more user friendly?

**Comment by FranciscoTGouveia** [comment] 2024-04-28 08:30
We were thinking of starting with a simple color picker widget that would sit on the page property of the Item we wanted to change color. Initially we would be able to select the color in a *CSS-agnostic* way ([a visual color picker](https://docs.gtk.org/gtk3/iface.ColorChooser.html) maybe) but this interface could later support more style aspects than just color, like `line-width` for example.

**Comment by amolenaar** [comment] 2024-04-28 12:21
Maybe this also ties in with #2137 (style sheet presets)?

Also, we have not used CSS id's and classes yet, so you can also use those to your advantage :smiley:. 

I do have a slight preference that we do not add styling info on the presentation elements directly. I'm aware though that it's a lot to ask from a user to learn CSS in order to change a color.

**Comment by 0lione** [comment] 2024-04-28 12:59
> Maybe this also ties in with #2137 (style sheet presets)?
> 
> Also, we have not used CSS id's and classes yet, so you can also use those to your advantage 😃.
> 
> I do have a slight preference that we do not add styling info on the presentation elements directly. I'm aware though that it's a lot to ask from a user to learn CSS in order to change a color.

But I thought that referencing with id's was not supported in gaphor

**Closed** 2024-11-30 22:33 UTC
Labels: feature
