### ISSUE TITLE
Corners in flow object are not included in parent (Activity) object (They don't move with the Activity).

### ISSUE THREAD

**Issue by 2old4it** [gaphor/gaphor#2767] opened 2023-10-10 16:40 UTC
### Describe the bug
It is not a major issue but more a little annoying.
If I add a corner to a flow in an Activity that corner can't be moved together with everything else inside the Activity.
The screenshots shows the effect.

### To Reproduce
1. Open a new SysML model in Gaphor.
2. Go to Concept Level -> Behavior -> Use Case Function 1
3. Add new Activity (make it a bit bigger)
4. Drag the 2 actions and the flow into the Activity
5. Select the Activity and drag it across the canvas (everything is moving)
6. Select the flow and add a corner
7. Select the Activity and drag it across the canvas.

### Expected behavior
Everything dragged into a parent should be moveable if you move the parent.

### Screenshots
![gaphor1](https://github.com/gaphor/gaphor/assets/76972837/bd97a1e7-d4a7-4e46-af36-b563939628af)
![gaphor2](https://github.com/gaphor/gaphor/assets/76972837/eb77c150-5cd7-4e4f-945b-e4da15ea048e)

### OS
- [X] Linux (Linux 5.15.128-1-MANJARO 1 SMP PREEMPT Sat Aug 26 17:22:47 UTC 2023 x86_64 GNU/Linux)
- [ ] macOS
- [ ] Windows

### Version
Version of Gaphor: 2.21.0
> pip list:

gaphas                        3.11.3
gaphor                        2.21.0

> python --version
Python 3.11.5

### Additional information
I have a large Activity with a lot of Actions to make it readable I need to add some corners to the flows.

**Comment by amolenaar** [comment] 2024-04-25 07:44
I'll close this issue, since we also have #3071, which covers the same issue. There has been some discussion on that issue already.

Duplicate of #3071

**Closed by amolenaar** 2024-04-25 07:44 UTC
