### ISSUE TITLE
Rectilinear straight line looks strange

### ISSUE THREAD

**Issue by alensiljak** [gaphor/gaphor#2738] opened 2023-09-30 16:02 UTC
### Describe the bug
When an association is set to be recti-linear, but is actually straight due to the layout of the elements, the arrow is still drawn at an angle. See the screenshot below.

### To Reproduce
1. Create two Component elements, one above the other on a diagram.
2. Create a direct association from the top to the bottom element.
3. Set the association to be rectilinear.
4. Observe how it appears on the diagram.

### Expected behavior
I'd expect the line to be straight, including the arrow. The green dot might probably be in the middle.

### Screenshots

![image](https://github.com/gaphor/gaphor/assets/462445/ecad2939-e877-4de0-b0d7-f63cd7d442ff)

![image](https://github.com/gaphor/gaphor/assets/462445/70509760-13d6-4a55-a083-5218182a0773)

### OS
- [x] Windows

### Version
Version of Gaphor: 2.21.0

**Comment by amolenaar** [comment] 2023-10-01 10:45
Hi @alensiljak,

Indeed this line drawing style is not ideal.

I think this is a duplicate of #2503.

**Comment by alensiljak** [comment] 2023-10-02 08:44
Yes, looks like that. That issue is a bit broad, though, so if you want to keep this one as a specific sub-item, that's ok.

**Comment by ebousse** [comment] 2024-02-05 13:28
I made a small video to illustrate the arrow edge angle problem that appears in some cases:

[Capture vidéo du 2024-02-05 14-25-16.webm](https://github.com/gaphor/gaphor/assets/5868014/5f31c870-1e72-490a-bd24-5bc3e13c8173)

**Comment by danyeaw** [comment] 2024-02-14 23:36
I don't think there is anything specific about associations, since this impacts all rectilinear line drawing. Let's close this in favor of https://github.com/gaphor/gaphor/issues/2486

@ebousse, thanks for the video, would you mind attaching it to the original issue?

**Closed by danyeaw** 2024-02-14 23:36 UTC
Labels: feature
