### ISSUE TITLE
Allow user to define his own "diagram kinds" and his own "shapes"

### ISSUE THREAD

**Issue by tomaszdrozdz** [gaphor/gaphor#876] opened 2021-07-04 17:19 UTC
How about adding more diagrams kinds like "electronic circuits" ?

And how about 
- to allow user to define his own  "diagram kinds" 
- and even allow user to define his own "shapes" ?

**Comment by amolenaar** [comment] 2021-07-07 13:44
Hi @tomaszdrozdz,

Can you explain a little more? Gaphor has no concept of diagram kinds (you can put basically everything in a diagram). It's up to the user to organize and structure the modeling concepts. What would you expect from a "electronic circuits" diagram?

You can define your own shapes by providing a ModelingLanguage. You's have to code one in Python and it will be automatically picked up when Gaphor starts.

NB. For packaged builds for windows, mac and linux we still need a plugin mechanism, so people can install plugins alongside the packaged application.

**Comment by amolenaar** [comment] 2021-09-18 11:52
Closed as a duplicate of #973: ticket provides more guidance.

**Closed by amolenaar** 2021-09-18 11:52 UTC
