### ISSUE TITLE
Error when creating SysML blocks and moving ports around

### ISSUE THREAD

**Issue by sz332** [gaphor/gaphor#2453] opened 2023-07-10 17:04 UTC
### To Reproduce

- Create a new empty model
- Select Profile: SysML
- Add block: Block1
- Add block: Block2
- Create new diagram: new internal block diagram
- Drag in Block1 and Block2
- Select proxy port, add it to Block 1
- Select proxy port, add it to Block 2
- Connect the two ports with a connector
- Move one of the ports outside from the Block

![image](https://github.com/gaphor/gaphor/assets/8182138/2c1ddc91-7d2c-4b4a-80ca-e403d9e6094c)

Gaphor version:         2.19.2
Operating System:       Windows (10)
Display:                GdkWin32Display
Python version:         3.11.4
GTK version:            4.10.4
Adwaita version:        1.3.1
GtkSourceView version:  5.8.0
Cairo version:          1.17.8
Pango version:          1.50.14
PyGObject version:      3.44.1
Pycairo version:        1.24.0
pygit2/libgit2 version: 1.12.2  / 1.6.4

Errors:

Time since application startup: 0:00:40
|Traceback (most recent call last):
|  File "C:\Program Files\Gaphor\gaphas\view\gtkview.pyc", line 506, in do_snapshot
|  File "C:\Program Files\Gaphor\gaphas\painter\chain.pyc", line 30, in paint
|  File "C:\Program Files\Gaphor\gaphor\diagram\painter.pyc", line 53, in paint
|  File "C:\Program Files\Gaphor\gaphor\diagram\painter.pyc", line 28, in paint_item
|  File "C:\Program Files\Gaphor\gaphor\core\modeling\diagram.pyc", line 281, in style
|  File "C:\Program Files\Gaphor\gaphor\core\modeling\stylesheet.pyc", line 106, in match
|  File "C:\Program Files\Gaphor\gaphor\core\styling\__init__.pyc", line 137, in match
|  File "C:\Program Files\Gaphor\gaphor\core\styling\__init__.pyc", line 88, in merge_styles
|IndexError: tuple index out of range
└─────────────────────────────╌┄┈
Time since application startup: 0:00:40
|Traceback (most recent call last):
|  File "C:\Program Files\Gaphor\gaphas\view\gtkview.pyc", line 506, in do_snapshot
|  File "C:\Program Files\Gaphor\gaphas\painter\chain.pyc", line 30, in paint
|  File "C:\Program Files\Gaphor\gaphor\diagram\painter.pyc", line 53, in paint
|  File "C:\Program Files\Gaphor\gaphor\diagram\painter.pyc", line 28, in paint_item
|  File "C:\Program Files\Gaphor\gaphor\core\modeling\diagram.pyc", line 281, in style
|  File "C:\Program Files\Gaphor\gaphor\core\modeling\stylesheet.pyc", line 106, in match
|  File "C:\Program Files\Gaphor\gaphor\core\styling\__init__.pyc", line 137, in match
|  File "C:\Program Files\Gaphor\gaphor\core\styling\__init__.pyc", line 88, in merge_styles
|IndexError: tuple index out of range
└─────────────────────────────╌┄┈
Time since application startup: 0:00:40
|Traceback (most recent call last):
|  File "C:\Program Files\Gaphor\gaphas\view\gtkview.pyc", line 506, in do_snapshot
|  File "C:\Program Files\Gaphor\gaphas\painter\chain.pyc", line 30, in paint
|  File "C:\Program Files\Gaphor\gaphor\diagram\painter.pyc", line 53, in paint
|  File "C:\Program Files\Gaphor\gaphor\diagram\painter.pyc", line 28, in paint_item
|  File "C:\Program Files\Gaphor\gaphor\core\modeling\diagram.pyc", line 281, in style
|  File "C:\Program Files\Gaphor\gaphor\core\modeling\stylesheet.pyc", line 106, in match
|  File "C:\Program Files\Gaphor\gaphor\core\styling\__init__.pyc", line 137, in match
|  File "C:\Program Files\Gaphor\gaphor\core\styling\__init__.pyc", line 88, in merge_styles
|IndexError: tuple index out of range
└─────────────────────────────╌┄┈
Time since application startup: 0:00:40
|Traceback (most recent call last):
|  File "C:\Program Files\Gaphor\gaphas\view\gtkview.pyc", line 506, in do_snapshot
|  File "C:\Program Files\Gaphor\gaphas\painter\chain.pyc", line 30, in paint
|  File "C:\Program Files\Gaphor\gaphor\diagram\painter.pyc", line 53, in paint
|  File "C:\Program Files\Gaphor\gaphor\diagram\painter.pyc", line 28, in paint_item
|  File "C:\Program Files\Gaphor\gaphor\core\modeling\diagram.pyc", line 281, in style
|  File "C:\Program Files\Gaphor\gaphor\core\modeling\stylesheet.pyc", line 106, in match
|  File "C:\Program Files\Gaphor\gaphor\core\styling\__init__.pyc", line 137, in match
|  File "C:\Program Files\Gaphor\gaphor\core\styling\__init__.pyc", line 88, in merge_styles
|IndexError: tuple index out of range
└─────────────────────────────╌┄┈
Time since application startup: 0:00:41
|Traceback (most recent call last):
|  File "C:\Program Files\Gaphor\gaphas\view\gtkview.pyc", line 506, in do_snapshot
|  File "C:\Program Files\Gaphor\gaphas\painter\chain.pyc", line 30, in paint
|  File "C:\Program Files\Gaphor\gaphor\diagram\painter.pyc", line 53, in paint
|  File "C:\Program Files\Gaphor\gaphor\diagram\painter.pyc", line 28, in paint_item
|  File "C:\Program Files\Gaphor\gaphor\core\modeling\diagram.pyc", line 281, in style
|  File "C:\Program Files\Gaphor\gaphor\core\modeling\stylesheet.pyc", line 106, in match
|  File "C:\Program Files\Gaphor\gaphor\core\styling\__init__.pyc", line 137, in match
|  File "C:\Program Files\Gaphor\gaphor\core\styling\__init__.pyc", line 88, in merge_styles
|IndexError: tuple index out of range
└─────────────────────────────╌┄┈
Time since application startup: 0:00:41
|Traceback (most recent call last):
|  File "C:\Program Files\Gaphor\gaphas\view\gtkview.pyc", line 506, in do_snapshot
|  File "C:\Program Files\Gaphor\gaphas\painter\chain.pyc", line 30, in paint
|  File "C:\Program Files\Gaphor\gaphor\diagram\painter.pyc", line 53, in paint
|  File "C:\Program Files\Gaphor\gaphor\diagram\painter.pyc", line 28, in paint_item
|  File "C:\Program Files\Gaphor\gaphor\core\modeling\diagram.pyc", line 281, in style
|  File "C:\Program Files\Gaphor\gaphor\core\modeling\stylesheet.pyc", line 106, in match
|  File "C:\Program Files\Gaphor\gaphor\core\styling\__init__.pyc", line 137, in match
|  File "C:\Program Files\Gaphor\gaphor\core\styling\__init__.pyc", line 88, in merge_styles
|IndexError: tuple index out of range
└─────────────────────────────╌┄┈
Time since application startup: 0:00:41
|Traceback (most recent call last):
|  File "C:\Program Files\Gaphor\gaphas\view\gtkview.pyc", line 506, in do_snapshot
|  File "C:\Program Files\Gaphor\gaphas\painter\chain.pyc", line 30, in paint
|  File "C:\Program Files\Gaphor\gaphor\diagram\painter.pyc", line 53, in paint
|  File "C:\Program Files\Gaphor\gaphor\diagram\painter.pyc", line 28, in paint_item
|  File "C:\Program Files\Gaphor\gaphor\core\modeling\diagram.pyc", line 281, in style
|  File "C:\Program Files\Gaphor\gaphor\core\modeling\stylesheet.pyc", line 106, in match
|  File "C:\Program Files\Gaphor\gaphor\core\styling\__init__.pyc", line 137, in match
|  File "C:\Program Files\Gaphor\gaphor\core\styling\__init__.pyc", line 88, in merge_styles
|IndexError: tuple index out of range
└─────────────────────────────╌┄┈
Time since application startup: 0:00:41
|Traceback (most recent call last):
|  File "C:\Program Files\Gaphor\gaphas\view\gtkview.pyc", line 506, in do_snapshot
|  File "C:\Program Files\Gaphor\gaphas\painter\chain.pyc", line 30, in paint
|  File "C:\Program Files\Gaphor\gaphor\diagram\painter.pyc", line 53, in paint
|  File "C:\Program Files\Gaphor\gaphor\diagram\painter.pyc", line 28, in paint_item
|  File "C:\Program Files\Gaphor\gaphor\core\modeling\diagram.pyc", line 281, in style
|  File "C:\Program Files\Gaphor\gaphor\core\modeling\stylesheet.pyc", line 106, in match
|  File "C:\Program Files\Gaphor\gaphor\core\styling\__init__.pyc", line 137, in match
|  File "C:\Program Files\Gaphor\gaphor\core\styling\__init__.pyc", line 88, in merge_styles
|IndexError: tuple index out of range
└─────────────────────────────╌┄┈
Time since application startup: 0:00:41
|Traceback (most recent call last):
|  File "C:\Program Files\Gaphor\gaphas\view\gtkview.pyc", line 506, in do_snapshot
|  File "C:\Program Files\Gaphor\gaphas\painter\chain.pyc", line 30, in paint
|  File "C:\Program Files\Gaphor\gaphor\diagram\painter.pyc", line 53, in paint
|  File "C:\Program Files\Gaphor\gaphor\diagram\painter.pyc", line 28, in paint_item
|  File "C:\Program Files\Gaphor\gaphor\core\modeling\diagram.pyc", line 281, in style
|  File "C:\Program Files\Gaphor\gaphor\core\modeling\stylesheet.pyc", line 106, in match
|  File "C:\Program Files\Gaphor\gaphor\core\styling\__init__.pyc", line 137, in match
|  File "C:\Program Files\Gaphor\gaphor\core\styling\__init__.pyc", line 88, in merge_styles
|IndexError: tuple index out of range
└─────────────────────────────╌┄┈
Time since application startup: 0:00:41
|Traceback (most recent call last):
|  File "C:\Program Files\Gaphor\gaphas\view\gtkview.pyc", line 506, in do_snapshot
|  File "C:\Program Files\Gaphor\gaphas\painter\chain.pyc", line 30, in paint
|  File "C:\Program Files\Gaphor\gaphor\diagram\painter.pyc", line 53, in paint
|  File "C:\Program Files\Gaphor\gaphor\diagram\painter.pyc", line 28, in paint_item
|  File "C:\Program Files\Gaphor\gaphor\core\modeling\diagram.pyc", line 281, in style
|  File "C:\Program Files\Gaphor\gaphor\core\modeling\stylesheet.pyc", line 106, in match
|  File "C:\Program Files\Gaphor\gaphor\core\styling\__init__.pyc", line 137, in match
|  File "C:\Program Files\Gaphor\gaphor\core\styling\__init__.pyc", line 88, in merge_styles
|IndexError: tuple index out of range
└─────────────────────────────╌┄┈
Time since application startup: 0:00:41
|Traceback (most recent call last):
|  File "C:\Program Files\Gaphor\gaphas\view\gtkview.pyc", line 506, in do_snapshot
|  File "C:\Program Files\Gaphor\gaphas\painter\chain.pyc", line 30, in paint
|  File "C:\Program Files\Gaphor\gaphor\diagram\painter.pyc", line 53, in paint
|  File "C:\Program Files\Gaphor\gaphor\diagram\painter.pyc", line 28, in paint_item
|  File "C:\Program Files\Gaphor\gaphor\core\modeling\diagram.pyc", line 281, in style
|  File "C:\Program Files\Gaphor\gaphor\core\modeling\stylesheet.pyc", line 106, in match
|  File "C:\Program Files\Gaphor\gaphor\core\styling\__init__.pyc", line 137, in match
|  File "C:\Program Files\Gaphor\gaphor\core\styling\__init__.pyc", line 88, in merge_styles
|IndexError: tuple index out of range
└─────────────────────────────╌┄┈
Time since application startup: 0:00:41
|Traceback (most recent call last):
|  File "C:\Program Files\Gaphor\gaphas\view\gtkview.pyc", line 506, in do_snapshot
|  File "C:\Program Files\Gaphor\gaphas\painter\chain.pyc", line 30, in paint
|  File "C:\Program Files\Gaphor\gaphor\diagram\painter.pyc", line 53, in paint
|  File "C:\Program Files\Gaphor\gaphor\diagram\painter.pyc", line 28, in paint_item
|  File "C:\Program Files\Gaphor\gaphor\core\modeling\diagram.pyc", line 281, in style
|  File "C:\Program Files\Gaphor\gaphor\core\modeling\stylesheet.pyc", line 106, in match
|  File "C:\Program Files\Gaphor\gaphor\core\styling\__init__.pyc", line 137, in match
|  File "C:\Program Files\Gaphor\gaphor\core\styling\__init__.pyc", line 88, in merge_styles
|IndexError: tuple index out of range
└─────────────────────────────╌┄┈
Time since application startup: 0:00:41
|Traceback (most recent call last):
|  File "C:\Program Files\Gaphor\gaphas\view\gtkview.pyc", line 506, in do_snapshot
|  File "C:\Program Files\Gaphor\gaphas\painter\chain.pyc", line 30, in paint
|  File "C:\Program Files\Gaphor\gaphor\diagram\painter.pyc", line 53, in paint
|  File "C:\Program Files\Gaphor\gaphor\diagram\painter.pyc", line 28, in paint_item
|  File "C:\Program Files\Gaphor\gaphor\core\modeling\diagram.pyc", line 281, in style
|  File "C:\Program Files\Gaphor\gaphor\core\modeling\stylesheet.pyc", line 106, in match
|  File "C:\Program Files\Gaphor\gaphor\core\styling\__init__.pyc", line 137, in match
|  File "C:\Program Files\Gaphor\gaphor\core\styling\__init__.pyc", line 88, in merge_styles
|IndexError: tuple index out of range
└─────────────────────────────╌┄┈
Time since application startup: 0:00:41
|Traceback (most recent call last):
|  File "C:\Program Files\Gaphor\gaphas\view\gtkview.pyc", line 506, in do_snapshot
|  File "C:\Program Files\Gaphor\gaphas\painter\chain.pyc", line 30, in paint
|  File "C:\Program Files\Gaphor\gaphor\diagram\painter.pyc", line 53, in paint
|  File "C:\Program Files\Gaphor\gaphor\diagram\painter.pyc", line 28, in paint_item
|  File "C:\Program Files\Gaphor\gaphor\core\modeling\diagram.pyc", line 281, in style
|  File "C:\Program Files\Gaphor\gaphor\core\modeling\stylesheet.pyc", line 106, in match
|  File "C:\Program Files\Gaphor\gaphor\core\styling\__init__.pyc", line 137, in match
|  File "C:\Program Files\Gaphor\gaphor\core\styling\__init__.pyc", line 88, in merge_styles
|IndexError: tuple index out of range
└─────────────────────────────╌┄┈
Time since application startup: 0:00:41
|Traceback (most recent call last):
|  File "C:\Program Files\Gaphor\gaphas\view\gtkview.pyc", line 506, in do_snapshot
|  File "C:\Program Files\Gaphor\gaphas\painter\chain.pyc", line 30, in paint
|  File "C:\Program Files\Gaphor\gaphor\diagram\painter.pyc", line 53, in paint
|  File "C:\Program Files\Gaphor\gaphor\diagram\painter.pyc", line 28, in paint_item
|  File "C:\Program Files\Gaphor\gaphor\core\modeling\diagram.pyc", line 281, in style
|  File "C:\Program Files\Gaphor\gaphor\core\modeling\stylesheet.pyc", line 106, in match
|  File "C:\Program Files\Gaphor\gaphor\core\styling\__init__.pyc", line 137, in match
|  File "C:\Program Files\Gaphor\gaphor\core\styling\__init__.pyc", line 88, in merge_styles
|IndexError: tuple index out of range
└─────────────────────────────╌┄┈
Time since application startup: 0:00:41
|Traceback (most recent call last):
|  File "C:\Program Files\Gaphor\gaphas\view\gtkview.pyc", line 506, in do_snapshot
|  File "C:\Program Files\Gaphor\gaphas\painter\chain.pyc", line 30, in paint
|  File "C:\Program Files\Gaphor\gaphor\diagram\painter.pyc", line 53, in paint
|  File "C:\Program Files\Gaphor\gaphor\diagram\painter.pyc", line 28, in paint_item
|  File "C:\Program Files\Gaphor\gaphor\core\modeling\diagram.pyc", line 281, in style
|  File "C:\Program Files\Gaphor\gaphor\core\modeling\stylesheet.pyc", line 106, in match
|  File "C:\Program Files\Gaphor\gaphor\core\styling\__init__.pyc", line 137, in match
|  File "C:\Program Files\Gaphor\gaphor\core\styling\__init__.pyc", line 88, in merge_styles
|IndexError: tuple index out of range
└─────────────────────────────╌┄┈
Time since application startup: 0:00:41
|Traceback (most recent call last):
|  File "C:\Program Files\Gaphor\gaphas\view\gtkview.pyc", line 506, in do_snapshot
|  File "C:\Program Files\Gaphor\gaphas\painter\chain.pyc", line 30, in paint
|  File "C:\Program Files\Gaphor\gaphor\diagram\painter.pyc", line 53, in paint
|  File "C:\Program Files\Gaphor\gaphor\diagram\painter.pyc", line 28, in paint_item
|  File "C:\Program Files\Gaphor\gaphor\core\modeling\diagram.pyc", line 281, in style
|  File "C:\Program Files\Gaphor\gaphor\core\modeling\stylesheet.pyc", line 106, in match
|  File "C:\Program Files\Gaphor\gaphor\core\styling\__init__.pyc", line 137, in match
|  File "C:\Program Files\Gaphor\gaphor\core\styling\__init__.pyc", line 88, in merge_styles
|IndexError: tuple index out of range
└─────────────────────────────╌┄┈

### Expected behavior

It should not be possible to move the port out from the block ownership.

### OS
- [ ] Linux (Please put in notes the specific distro)
- [ ] macOS
- [X] Windows

### Version
Version of Gaphor: 2.19.2

**Comment by amolenaar** [comment] 2023-07-12 12:38
Hi @sz332, thanks for the report.

This issue has been resolved by #2460.

@danyeaw This is the third issue, caused by the same error. I think we should do a new release :wink:.

**Closed by amolenaar** 2023-07-12 12:38 UTC
Labels: bug
