### ISSUE TITLE
Gaphor crashes when trying to save or open a project - Ubuntu 20.04.6 LTS

### ISSUE THREAD

**Issue by Boyle4000** [gaphor/gaphor#2717] opened 2023-09-22 10:34 UTC
### Describe the bug
I just recently installed Gaphor (It looks and feels like a very nice tool. Thanks). When I tried to save my first project, Gaphor didn't react anymore to my input. It was not completely frozen. The GUI was reacting to my cursor but interacting with the buttons did not lead to any actions. The same behavior occurs when I tried to open a project. I would need to manually close the application.  

### To Reproduce
1. Go to 'Save as' or 'Open'
2. Click on 'Save as' to open dialogue window (or use ctr +shift + s)
3. Save file 
4. Upon closing of window and returning to Gaphor, GUI becomes unresponsive and the file is not saved
5. Unresponsive Gaphor cannot be closed from the sidebar. Only through the Ubuntu process tool or the top bar Gaphor dialogue

### Expected behavior
To continue operating Gaphor

### Screenshots
No error messages

### OS
Ubuntu 20.04.6 LTS

### Version
Version of Gaphor: 2.21.0 (flatpak)

**Comment by amolenaar** [comment] 2023-09-24 11:13
Hi @Boyle4000, thank you for your report.

Do you want to run Gaphor from a terminal (`flatpak run org.gaphor.Gaphor`) and see if there are any exceptions logged in the terminal?

**Comment by amolenaar** [comment] 2023-10-01 10:10
I'm wondering if this is an incompatibility with [Flatpak Portals](https://docs.flatpak.org/en/latest/desktop-integration.html), since those are used under the hood for file dialog related things.

**Comment by amolenaar** [comment] 2023-10-06 07:44
I was not able to reproduce it on a (fresh) Ubuntu 20.04 virtual machine.

There was a [similar report](https://matrix.to/#/!pJkHfTcdAUntpUNxJf:matrix.org/$169648911413ZSmvU:mozilla.org?via=gnome.org&via=matrix.org&via=libera.chat) in the GNOME Python Matrix channel, though.

**Comment by amolenaar** [comment] 2023-12-27 22:33
@Boyle4000 Is this still a problem? Have you tried another Flatpak bundle in the meantime time?

**Comment by amolenaar** [comment] 2024-01-08 10:30
@Boyle4000 With Gaphor 2.23, we dropped the filesystem permissions from Gaphor: models can be opened via Flatpak Portals (a more secure alternative to direct file access).

This may fix your issue.

**Comment by amolenaar** [comment] 2024-03-18 15:21
I'm closing this issue. A few improvements have been implemented to prevent this scenario. Let's see if it's enough.

**Closed by amolenaar** 2024-03-18 15:21 UTC
