### ISSUE TITLE
Blocks do not show parts when show parts button is set

### ISSUE THREAD

**Issue by mikekidner** [gaphor/gaphor#2613] opened 2023-08-08 13:03 UTC
### Describe the bug
The list of parts is not shown when the _Show Parts_ button is set to "on"

### To Reproduce
1. Make and block with some component blocks
2. With the block highlighted, Click on 'Show Parts'
3. See the parts compartment appear on the block
4. See it has no content

### Expected behavior
The component parts should be listed

### Screenshots
<img width="838" alt="Screen Shot 2023-08-08 at 10 28 43 pm" src="https://github.com/gaphor/gaphor/assets/50702106/b3c7a843-3ba0-4203-87e2-c1fc9fa4d9f3">
The diargam showing no listed parts

<img width="889" alt="Screen Shot 2023-08-08 at 10 29 02 pm" src="https://github.com/gaphor/gaphor/assets/50702106/a13b11c9-49f4-4cb3-84b5-d9b8d51a653e">
The bdd of the referenced block

### OS
- [ ] Linux (Please put in notes the specific distro)
- [x] macOS
- [ ] Windows

### Version
Version of Gaphor: 2.20

**Comment by danyeaw** [comment] 2023-08-08 13:26
Thanks @mikekidner, I can reproduce this as well :+1:

**Comment by marek-piirikivi** [comment] 2023-08-10 03:49
@danyeaw I started working on this. Fixed by removing `not a.association` from the predicate (and also included "shared" as part indicator for aggregation). I'll open PR.

Do you think that the references could also be broken because of that? Association seems to be set on every ownedAttribute from where these relations are pulled :thinking:

**Comment by danyeaw** [comment] 2023-08-10 19:53
@marek-piirikivi Ya, I agree that references are broken as well.

**Closed** 2023-08-11 02:55 UTC
Labels: bug
