### ISSUE TITLE
Reorder model elements in the model browser/tree

### ISSUE THREAD

**Issue by shobeira** [gaphor/gaphor#2594] opened 2023-08-02 10:14 UTC
### Is your feature request related to a problem?
Showing a long name underneath of element on diagrams.

### Describe the solution you'd like
Reorder elements as I wish without restriction of alphabetical order.

### Describe alternatives you've considered
Currently model elements are sorted alphabetically and I use nested numbering format to order them the way I need.

**Comment by marek-piirikivi** [comment] 2023-08-08 03:52
> Currently model elements are sorted alphabetically and I use nested numbering format to order them the way I need.

I would like to add that this system collapses as soon as you have more than 10 items in the list.

**Comment by amolenaar** [comment] 2024-02-24 19:29
Closing as duplicate of #2334.

I think we can support different types of ordering/sorting. Changing the order manually is a lot of hassle, since we also have to store that order.

**Closed by amolenaar** 2024-02-24 19:29 UTC
Labels: feature
