### ISSUE TITLE
Codegen not working

### ISSUE THREAD

**Issue by xcadush** [gaphor/gaphor#2827] opened 2023-11-10 11:00 UTC
### Describe the bug
Dear all, 
I'm currently trying to translate the `coffee-machine.gaphor` example into a Python code through the `coder.py` script, but the latter gives errors and stops the translation.

Gaphor works flawlessly and I assume there are no errors in the model or in the script. 

Am I wrong or there is the possibility to parse `.gaphor` models into `.py` data structures? If so, what are the correct inputs or model formats for doing that?

This functionality would be incredibly useful for linking sysml models to other python scripts for various analyses.

Thank you in advance.

### To Reproduce
1. `cd gaphor_install_folder`
2. `python3 ./gaphor/codegen/coder.py -o ../tests/output.py -r ./models/SysML.override -s SysML:models/SysML.gaphor ./examples/coffee-machine.gaphor`

### Output Error
```
$ python3 ./gaphor/codegen/coder.py -o ../tests/output.py -r ./models/SysML.override -s SysML:models/SysML.gaphor ./examples/coffee-machine.gaphor

No translations were found for language it_IT.UTF-8: [Errno 2] No translation file found for domain: 'gaphor'
Traceback (most recent call last):

  File "<install_path> ./gaphor/codegen/coder.py", line 508, in <module>
    main(args.modelfile, supermodelfiles, args.overridesfile, args.outfile)

  File "<install_path> ./gaphor/codegen/coder.py", line 102, in main
    [
  File "<install_path> ./gaphor/codegen/coder.py", line 103, in <listcomp>
    (load_modeling_language(lang), load_model(f, modeling_language))
    
  File "<install_path> ./gaphor/codegen/coder.py", line 133, in load_modeling_language
    return initialize("gaphor.modelinglanguages", [lang])[lang]
KeyError: 'SysML'
```
If the `SysML.override` is not included, the `test.py` file is partially generated as:
```
# This file is generated by coder.py. DO NOT EDIT!
# ruff: noqa: F401, E402, F811
# fmt: off

from __future__ import annotations

from gaphor.core.modeling.properties import (
    association,
    attribute as _attribute,
    derived,
    derivedunion,
    enumeration as _enumeration,
    redefine,
    relation_many,
    relation_one,
)

class Domain():
    None: relation_many[Barista]
    None: relation_many[Espresso Machine]
    None: relation_many[Roasted Coffee]
    None: relation_many[Coffee Grinder]
    None: relation_many[Water Supply]
    None: relation_many[Customer]

class Barista():
    pass

class Espresso Machine():
    pass

class Roasted Coffee():
    pass

class Water Tank():
    pass

class Espresso Machine():
    controller: relation_many[Controller]
    grouphead: relation_many[Grouphead]
    hmi: relation_many[HMI]
    portafilter: relation_many[Portafilter]
    waterHeater: relation_many[Water Heater]
    waterPump: relation_many[Water Pump]
    waterTank: relation_many[Water Tank]

class Water Tank():
    pass

class Water Pump():
    pass

class Water Heater():
    pass

class Controller Commands Heatup():
    pass

class Activity():
    pass

class Example Technology Requirement():
    pass

class System():
    dc Motor: relation_many[DC Motor]
    ecu: relation_many[ECU]
    ir Transceiver: relation_many[IR Transceiver]

class ECU():
    pass

class DC Motor():
    pass

class IR Transceiver():
    pass

class Activity():
    pass

class Interaction():
    pass

class Brew espresso():
    pass

class Coffee Grinder():
    pass

class Water Supply():
    pass

class Customer():
    pass

class Heatup Time():
    pass

class 1 Cup Button():
    pass

class Portafilter():
    pass

class Controller():
    pass

class Grouphead():
    pass

class HMI():
    pass

class 900kPa of Water Pressure():
    pass

class State Machine():
    pass
```

### Expected behavior
Obtain a `test.py` file similar to `./gaphor/SysML/sysml.py`.

### OS
- [x] Linux (`Ubuntu 22.04.3 LTS`)
- [ ] macOS
- [ ] Windows

### Version
Version of Gaphor: 2.21.0 (the latest as for now)

**Comment by amolenaar** [comment] 2023-11-10 14:12
Hi @xcadush,

I would be quite surprised if the coder did work properly 😄.

The coffee machine model is using SysML, whereas the models are made with UML elements.
Also, our internal models adhere to certain conventions, so the coder can produce the right model code (the way we deal with derived associations, refer to elements in base models, etc.).

We do not believe in a generic coder that works for all projects. Instead you should create a coder that caters your needs and knows how to deal with the conventions you use in your model(s). The coder we use is a good starting point.

**Comment by xcadush** [comment] 2023-11-10 14:22
Thank you for the quick reply, I'll give it a try :)

**Comment by amolenaar** [comment] 2023-11-28 18:03
I'll close this ticket, since it's not a bug or feature request. If you want to to stay in contact, you can always join our Matrix channel at https://app.element.io/#/room/#gaphor_Lobby:gitter.im.

**Closed by amolenaar** 2023-11-28 18:03 UTC
