### ISSUE TITLE
Tool selection shortcuts not working

### ISSUE THREAD

**Issue by marek-piirikivi** [gaphor/gaphor#2067] opened 2023-02-05 05:44 UTC
### Describe the bug
Tool icons display shortcuts but do not do anything when keys are selected from the keyboard.

### To Reproduce
1. Have requirements diagram open
2. Press "r" key on the keyboard
3. Nothing happens

If possible, add the error report from `≡` (top-right menu) → `Tools` → `Error Reports`.

### Expected behavior
The expected behavior would be to have a requirements add tool active. The same as clicking the requirements icon in the toolbox with a mouse.

### Screenshots
Can not be shown with a screenshot.

### OS
- [x] Linux
- [ ] macOS
- [ ] Windows

### Version
Version of Gaphor: 2.16.0

### Additional information
Using: Linux Mint 21 Cinnamon.

The problem can be fixed by applying accelerator default mod mask to the state in Toolbox UI component's activate_shortcut() member function.

**Comment by marek-piirikivi** [comment] 2023-02-05 05:45
I would like to work on this.

**Comment by danyeaw** [comment] 2023-02-05 15:12
I am not able to reproduce this issue with the Flatpak or from source using openSUSE Tumbleweed with Wayland. The keyboard shortcuts aren't working at all for you, even when you have the diagram selected?

**Comment by amolenaar** [comment] 2023-02-05 20:02
@marek-piirikivi You have Caps-Lock enabled by any chance?

**Comment by marek-piirikivi** [comment] 2023-02-05 20:21
It appears that I have fift modifier key active (GTK mod 2 flag). Seems to be always on and according to the GTK documentation, it depends on the modifier mapping of the X server.

I have problems only with tool selection. Other shortcuts (such as rename active in the tree) works just fine.

**Comment by amolenaar** [comment] 2023-02-05 20:36
Thank you for helping out. I merged your PR.

**Closed by amolenaar** 2023-02-05 20:36 UTC
