### ISSUE TITLE
Crash when adding parameter nodes to activity nodes

### ISSUE THREAD

**Issue by Bambofy** [gaphor/gaphor#2433] opened 2023-07-07 20:04 UTC
### Describe the bug
When i try to add a parameter node to activities on an activity diagram, sometimes it causes the editor to crash. I have tried gaphor on both linux and OS X and it is happening on both OSes. I have captured the error logs for the first time the crash happened and is linked below.

[parameter-node-crash-report.txt](https://github.com/gaphor/gaphor/files/11985508/parameter-node-crash-report.txt)

Now after the editor has crashed, the editor seemingly crashes every time i try to add a action to an activity diagram. This functioned properly before and the previous crash due to the parameter node seems to have caused this too. I have added 2 error reports which occured after that first crash due to the parameter node.

[activity-node-crash-report-1.txt](https://github.com/gaphor/gaphor/files/11985505/activity-node-crash-report-1.txt)
[activity-node-crash-report-2.txt](https://github.com/gaphor/gaphor/files/11985507/activity-node-crash-report-2.txt)

### To Reproduce
1. Create a blank diagram.
2. Add an activity node to the diagram.
3. Add an action node to the diagram outside of the activity node
4. Add a parameter node to the activity node.

### Expected behavior
gaphor does not crash when adding parameter nodes.

### OS
- [X] Linux (Please put in notes the specific distro)
- [X] macOS
- [ ] Windows

### Version
Version of Gaphor: 2.19.1

### Additional information
Linux distro: Ubuntu

**Comment by amolenaar** [comment] 2023-07-07 21:10
Hi @Bambofy, Thanks for reporting.

Indeed I can reproduce this locally with the Flatpak build (linux).

I suspect this error was introduced by https://github.com/gaphor/gaphor/pull/2329.

**Comment by amolenaar** [comment] 2023-07-08 12:41
I created a MR on GTK for this: https://gitlab.gnome.org/GNOME/gtk/-/merge_requests/6174.

**Comment by amolenaar** [comment] 2023-07-10 06:07
The issue is fixed in Gaphor 2.19.2.

However, I'd like to keep this issue open until a fix is proveded upstream.

**Closed** 2024-02-24 16:22 UTC
Labels: bug, upstream
